name: 'complex_dbt_project'
version: '1.0.0'
config-version: 2

profile: 'SHIVASD202504'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  complex_dbt_project:
    +tests:
      severity: warn
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: analytics

seeds:
  complex_dbt_project:
    +column_types:
      customer_id: varchar(50)
      order_id: varchar(50)
      payment_id: varchar(50)
    +schema: raw_raw